movement.species.map0,lesserSpottedDogfish
movement.variable.map0,stage0
movement.nsteps.year.map0,24
movement.initialAge.map0,0
movement.lastAge.map0,2
movement.file.map0,maps_nc/lesserSpottedDogfish.nc
movement.species.map1,lesserSpottedDogfish
movement.variable.map1,stage1
movement.nsteps.year.map1,24
movement.initialAge.map1,2
movement.lastAge.map1,11
movement.file.map1,maps_nc/lesserSpottedDogfish.nc
movement.species.map2,whiting
movement.variable.map2,stage0
movement.nsteps.year.map2,24
movement.initialAge.map2,0
movement.lastAge.map2,1
movement.file.map2,maps_nc/whiting.nc
movement.species.map3,whiting
movement.variable.map3,stage1
movement.nsteps.year.map3,24
movement.initialAge.map3,1
movement.lastAge.map3,2
movement.file.map3,maps_nc/whiting.nc
movement.species.map4,whiting
movement.variable.map4,stage2
movement.nsteps.year.map4,24
movement.initialAge.map4,2
movement.lastAge.map4,21
movement.file.map4,maps_nc/whiting.nc
movement.species.map5,poorCod
movement.variable.map5,stage0
movement.nsteps.year.map5,24
movement.initialAge.map5,0
movement.lastAge.map5,2
movement.file.map5,maps_nc/poorCod.nc
movement.species.map6,poorCod
movement.variable.map6,stage1
movement.nsteps.year.map6,24
movement.initialAge.map6,2
movement.lastAge.map6,4
movement.file.map6,maps_nc/poorCod.nc
movement.species.map7,cod
movement.variable.map7,stage0
movement.nsteps.year.map7,24
movement.initialAge.map7,0
movement.lastAge.map7,1
movement.file.map7,maps_nc/cod.nc
movement.species.map8,cod
movement.variable.map8,stage1
movement.nsteps.year.map8,24
movement.initialAge.map8,1
movement.lastAge.map8,4
movement.file.map8,maps_nc/cod.nc
movement.species.map9,cod
movement.variable.map9,stage2
movement.nsteps.year.map9,24
movement.initialAge.map9,4
movement.lastAge.map9,26
movement.file.map9,maps_nc/cod.nc
movement.species.map10,dragonet
movement.variable.map10,stage0
movement.nsteps.year.map10,24
movement.initialAge.map10,0
movement.lastAge.map10,7
movement.file.map10,maps_nc/dragonet.nc
movement.species.map11,redMullet
movement.variable.map11,stage0
movement.nsteps.year.map11,24
movement.initialAge.map11,0
movement.lastAge.map11,1
movement.file.map11,maps_nc/redMullet.nc
movement.species.map12,redMullet
movement.variable.map12,stage1
movement.nsteps.year.map12,24
movement.initialAge.map12,1
movement.lastAge.map12,12
movement.file.map12,maps_nc/redMullet.nc
movement.species.map13,sole
movement.variable.map13,stage0
movement.nsteps.year.map13,24
movement.initialAge.map13,0
movement.lastAge.map13,1
movement.file.map13,maps_nc/sole.nc
movement.species.map14,sole
movement.variable.map14,stage1
movement.nsteps.year.map14,24
movement.initialAge.map14,1
movement.lastAge.map14,3
movement.file.map14,maps_nc/sole.nc
movement.species.map15,sole
movement.variable.map15,stage2
movement.nsteps.year.map15,24
movement.initialAge.map15,3
movement.lastAge.map15,21
movement.file.map15,maps_nc/sole.nc
movement.species.map16,plaice
movement.variable.map16,stage0
movement.nsteps.year.map16,24
movement.initialAge.map16,0
movement.lastAge.map16,1
movement.file.map16,maps_nc/plaice.nc
movement.species.map17,plaice
movement.variable.map17,stage1
movement.nsteps.year.map17,24
movement.initialAge.map17,1
movement.lastAge.map17,3
movement.file.map17,maps_nc/plaice.nc
movement.species.map18,plaice
movement.variable.map18,stage2
movement.nsteps.year.map18,24
movement.initialAge.map18,3
movement.lastAge.map18,16
movement.file.map18,maps_nc/plaice.nc
movement.species.map19,horseMackerel
movement.variable.map19,stage0
movement.nsteps.year.map19,24
movement.initialAge.map19,0
movement.lastAge.map19,1
movement.file.map19,maps_nc/horseMackerel.nc
movement.species.map20,horseMackerel
movement.variable.map20,stage1
movement.nsteps.year.map20,24
movement.initialAge.map20,1
movement.lastAge.map20,4
movement.file.map20,maps_nc/horseMackerel.nc
movement.species.map21,horseMackerel
movement.variable.map21,stage2
movement.nsteps.year.map21,24
movement.initialAge.map21,4
movement.lastAge.map21,16
movement.file.map21,maps_nc/horseMackerel.nc
movement.species.map22,mackerel
movement.variable.map22,stage0
movement.nsteps.year.map22,24
movement.initialAge.map22,0
movement.lastAge.map22,1
movement.file.map22,maps_nc/mackerel.nc
movement.species.map23,mackerel
movement.variable.map23,stage1
movement.nsteps.year.map23,24
movement.initialAge.map23,1
movement.lastAge.map23,18
movement.file.map23,maps_nc/mackerel.nc
movement.species.map24,herring
movement.variable.map24,stage0
movement.nsteps.year.map24,24
movement.initialAge.map24,0
movement.lastAge.map24,11
movement.file.map24,maps_nc/herring.nc
movement.species.map25,sardine
movement.variable.map25,stage0
movement.nsteps.year.map25,24
movement.initialAge.map25,0
movement.lastAge.map25,16
movement.file.map25,maps_nc/sardine.nc
movement.species.map26,squids
movement.variable.map26,stage0
movement.nsteps.year.map26,24
movement.initialAge.map26,0
movement.lastAge.map26,3
movement.file.map26,maps_nc/squids.nc
movement.species.map27,pouting
movement.variable.map27,stage0
movement.nsteps.year.map27,24
movement.initialAge.map27,0
movement.lastAge.map27,1
movement.file.map27,maps_nc/pouting.nc
movement.species.map28,pouting
movement.variable.map28,stage1
movement.nsteps.year.map28,24
movement.initialAge.map28,1
movement.lastAge.map28,2
movement.file.map28,maps_nc/pouting.nc
movement.species.map29,pouting
movement.variable.map29,stage2
movement.nsteps.year.map29,24
movement.initialAge.map29,2
movement.lastAge.map29,5
movement.file.map29,maps_nc/pouting.nc
movement.species.map30,cuttlefish
movement.variable.map30,stage0
movement.nsteps.year.map30,24
movement.initialAge.map30,0
movement.lastAge.map30,1.75
movement.file.map30,maps_nc/cuttlefish.nc
movement.species.map31,cuttlefish
movement.variable.map31,stage1
movement.nsteps.year.map31,24
movement.initialAge.map31,1.75
movement.lastAge.map31,2
movement.file.map31,maps_nc/cuttlefish.nc
movement.species.map32,thornbackRay
movement.variable.map32,stage0
movement.nsteps.year.map32,24
movement.initialAge.map32,0
movement.lastAge.map32,15
movement.file.map32,maps_nc/thornbackRay.nc
